config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#         new_user_session GET    /user/login(.:format)                            devise/sessions#new
#             user_session POST   /user/login(.:format)                            devise/sessions#create
#     destroy_user_session DELETE /user/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /user/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /user/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /user/password(.:format)                         devise/passwords#update
#                          PUT    /user/password(.:format)                         devise/passwords#update
#                          POST   /user/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /user/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /user/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /user(.:format)                                  devise/registrations#update
#                          PUT    /user(.:format)                                  devise/registrations#update
#                          DELETE /user(.:format)                                  devise/registrations#destroy
#                          POST   /user(.:format)                                  devise/registrations#create
#                     root GET    /                                                home#top
#                 home_top GET    /home/top(.:format)                              home#top
#                home_help GET    /home/help(.:format)                             home#help
#             home_privacy GET    /home/privacy(.:format)                          home#privacy
#               home_terms GET    /home/terms(.:format)                            home#terms
#                    users GET    /users(.:format)                                 users#index
#                          POST   /users(.:format)                                 users#create
#                 new_user GET    /users/new(.:format)                             users#new
#                edit_user GET    /users/:id/edit(.:format)                        users#edit
#                     user GET    /users/:id(.:format)                             users#show
#                          PATCH  /users/:id(.:format)                             users#update
#                          PUT    /users/:id(.:format)                             users#update
#                          DELETE /users/:id(.:format)                             users#destroy
#       user_notifications GET    /user/notifications(.:format)                    user/notifications#index
#        user_notification GET    /user/notifications/:id(.:format)                user/notifications#show
#        user_speech_likes GET    /user/speeches/:speech_id/likes(.:format)        user/likes#index
#                          POST   /user/speeches/:speech_id/likes(.:format)        user/likes#create
#         user_speech_like DELETE /user/speeches/:speech_id/likes/:id(.:format)    user/likes#destroy
#     user_speech_comments POST   /user/speeches/:speech_id/comments(.:format)     user/comments#create
#      user_speech_comment DELETE /user/speeches/:speech_id/comments/:id(.:format) user/comments#destroy
#            user_speeches GET    /user/speeches(.:format)                         user/speeches#index
#                          POST   /user/speeches(.:format)                         user/speeches#create
#          new_user_speech GET    /user/speeches/new(.:format)                     user/speeches#new
#         edit_user_speech GET    /user/speeches/:id/edit(.:format)                user/speeches#edit
#              user_speech GET    /user/speeches/:id(.:format)                     user/speeches#show
#                          PATCH  /user/speeches/:id(.:format)                     user/speeches#update
#                          PUT    /user/speeches/:id(.:format)                     user/speeches#update
#                          DELETE /user/speeches/:id(.:format)                     user/speeches#destroy
#              admin_likes GET    /admin/likes(.:format)                           admin/likes#index
#              admin_users GET    /admin/users(.:format)                           admin/users#index

Rails.application.routes.draw do

  devise_for :user, :path_names => {:sign_in => 'login'}
  root to: "home#top"
  get 'home/top'
  get 'home/help'
  get 'home/privacy'
  get 'home/terms'
  resources :users
  namespace :user do
    resources :notifications, only: [:index, :show]
    resources :speeches do
      resources :likes, only: [:create, :destroy, :index]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :likes, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_message.html.erb
<% model.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if user_signed_in? && current_user.image.file.nil? %>
  <div class="alert alert-info alert-dismissible">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      ご自身のプロフィール画像を<%= link_to "こちら", edit_user_path(current_user) %>から設定してみましょう。
    </div>
  </div>
<% end %>

<% if user_signed_in? && current_user.speeches.empty? %>
  <div class="alert alert-info alert-dismissible">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      ご自身のスピーチも<%= link_to "こちら", new_user_speech_path %>から登録してみませんか？
    </div>
  </div>
<% end %>

<% if flash[:notice].present? %>
  <div class="alert alert-success alert-dismissible">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger alert-dismissible">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-main text-center ptm">
  <div class="footer-main__container">
    <div class="col-sm-3 pts">
      <%= link_to home_terms_path, target: "_blank" do %>
        利用規約
      <% end %>
    </div>
    <div class="col-sm-3 pts">
      <%= link_to home_privacy_path, target: "_blank" do %>
        プライバシーポリシー
      <% end %>
    </div>
    <div class="col-sm-3 pts">
      <%= link_to home_help_path, target: "_blank" do %>
        SpeechLinksの使い方
      <% end %>
    </div>
    <div class="col-sm-3 pts">
      <a href="https://kouch-sato.github.io/SpeechLinks_top/" target="_blank">
        トップページ
      </a>
    </div>
  </div>
  <div class="text-center pbl">
    <p>
      ©️2018  Kouch Sato
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <div class="navbar-brand">Speech Links</div>
      <% end %>
    </div>
    <div class="navbar-collapse collapse" id="main-navbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to user_speeches_path do %>
            <i class="fa fa-book"></i> スピーチ一覧
          <% end %>
        </li>
        <li>
          <%= link_to users_path do %>
            <i class="fa fa-users"></i> Speaker一覧
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_user_speech_path do %>
              <i class="fa fa-pencil-square-o"></i> スピーチ登録
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <i class="fa fa-user-circle"></i> <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "プロフィール", user_path(current_user) %>
              </li>
              <li>
                <%= link_to "プロフィール編集", edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "SpeechLinksの使い方", home_help_path %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
          <li>
            <%= render "shared/notification_dropdown" %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fa fa-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notification_dropdown.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
  <i class="fa fa-bell"></i>
  <span class="badge navbar-notification__badge">
    <%= current_user.notification.not_read.count %>
  </span>
</a>
<ul class="dropdown-menu" role="menu">
  <% current_user.notification.order("created_at DESC").limit(5).each do |notification| %>
    <% if notification.read %>
      <li class="navbar-notification__list">
    <% else %>
      <li class="navbar-notification__list unread">
    <% end %>
      <%= link_to user_notification_path(notification) do %>
        <p>
          <%= "#{notification.notified_by.name}さんが「#{notification.speech.title}」に#{notification.notified_type}しました" %>
        </p>
        <span>
          <%= time_ago_in_words(notification.created_at) %>前
        </span>
      <% end %>
      </li>
  <% end %>
  <div class="navbar-notification__more">
    <%= link_to "過去の一覧を見る", user_notifications_path %>
  </div>
</ul>