config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#         new_user_session GET    /user/login(.:format)                            devise/sessions#new
#             user_session POST   /user/login(.:format)                            devise/sessions#create
#     destroy_user_session DELETE /user/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /user/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /user/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /user/password(.:format)                         devise/passwords#update
#                          PUT    /user/password(.:format)                         devise/passwords#update
#                          POST   /user/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /user/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /user/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /user(.:format)                                  devise/registrations#update
#                          PUT    /user(.:format)                                  devise/registrations#update
#                          DELETE /user(.:format)                                  devise/registrations#destroy
#                          POST   /user(.:format)                                  devise/registrations#create
#                     root GET    /                                                home#top
#                 home_top GET    /home/top(.:format)                              home#top
#                home_help GET    /home/help(.:format)                             home#help
#             home_privacy GET    /home/privacy(.:format)                          home#privacy
#               home_terms GET    /home/terms(.:format)                            home#terms
#                    users GET    /users(.:format)                                 users#index
#                          POST   /users(.:format)                                 users#create
#                 new_user GET    /users/new(.:format)                             users#new
#                edit_user GET    /users/:id/edit(.:format)                        users#edit
#                     user GET    /users/:id(.:format)                             users#show
#                          PATCH  /users/:id(.:format)                             users#update
#                          PUT    /users/:id(.:format)                             users#update
#                          DELETE /users/:id(.:format)                             users#destroy
#       user_notifications GET    /user/notifications(.:format)                    user/notifications#index
#        user_notification GET    /user/notifications/:id(.:format)                user/notifications#show
#        user_speech_likes GET    /user/speeches/:speech_id/likes(.:format)        user/likes#index
#                          POST   /user/speeches/:speech_id/likes(.:format)        user/likes#create
#         user_speech_like DELETE /user/speeches/:speech_id/likes/:id(.:format)    user/likes#destroy
#     user_speech_comments POST   /user/speeches/:speech_id/comments(.:format)     user/comments#create
#      user_speech_comment DELETE /user/speeches/:speech_id/comments/:id(.:format) user/comments#destroy
#            user_speeches GET    /user/speeches(.:format)                         user/speeches#index
#                          POST   /user/speeches(.:format)                         user/speeches#create
#          new_user_speech GET    /user/speeches/new(.:format)                     user/speeches#new
#         edit_user_speech GET    /user/speeches/:id/edit(.:format)                user/speeches#edit
#              user_speech GET    /user/speeches/:id(.:format)                     user/speeches#show
#                          PATCH  /user/speeches/:id(.:format)                     user/speeches#update
#                          PUT    /user/speeches/:id(.:format)                     user/speeches#update
#                          DELETE /user/speeches/:id(.:format)                     user/speeches#destroy
#              admin_likes GET    /admin/likes(.:format)                           admin/likes#index
#              admin_users GET    /admin/users(.:format)                           admin/users#index

Rails.application.routes.draw do

  devise_for :user, :path_names => {:sign_in => 'login'}
  root to: "home#top"
  get 'home/top'
  get 'home/help'
  get 'home/privacy'
  get 'home/terms'
  resources :users
  namespace :user do
    resources :notifications, only: [:index, :show]
    resources :speeches do
      resources :likes, only: [:create, :destroy, :index]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :likes, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @new_speeches = Speech.all.order("created_at DESC").limit(3)
    @random_speeches = Speech.all.order("RAND()").limit(3)
    @commented_speeches = Comment.all.order("created_at DESC").limit(3).map(&:speech)
    if user_signed_in?
      @my_speeches = current_user.speeches.order("created_at DESC").limit(3)
      @my_liked_speeches = current_user.likes.order("created_at DESC").limit(3).map(&:speech)
    end
  end

  def help
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def home_help_meta_tags
    {
      title: 'ヘルプページ'
    }
  end

  def home_privacy_meta_tags
    {
      title: 'プライバシーポリシー'
    }
  end

  def home_terms_meta_tags
    {
      title: '利用規約'
    }
  end

  def home_top_meta_tags
    {
      title: 'トップページ'
    }
  end
end

app/views/home/_speeches.html.erb
<div class="row">
  <% speeches.each do |speech| %>
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title top-speech__title text-center">
            <%= speech.title %>
          </h3>
        </div>
        <div class="panel-body inner-m">
          <div class="mbm">
            <%= image_tag speech.user.image.thumb.url, class: "top-speech__image user-image" %>
            <span>
              <div class="top-speech__user-name">
                <%= link_to user_path(speech.user) do %>
                  <%= speech.user.name %>
                <% end %>
              </div>
              <span>
                (<%= speech.user.university %><%= speech.user.grade %>年)
              </span>
            </span>
          </div>

          <blockquote class="top-speech__overview">
            <%= speech.overview %>
          </blockquote>

          <div class="top-speech__info">
            最終更新:<%= speech.updated_at %>
            <span class="float-right">
            <% if speech.likes.count.nonzero? %>
              <span>
                <% if user_signed_in? && current_user.likes.find_by(speech_id: speech.id) %>
                  <i class="fa fa-check-circle speech-index-table__icon checked"></i>
                <% else %>
                  <i class="fa fa-check-circle speech-index-table__icon"></i>
                <% end %>
                <%= speech.likes.count %>
              </span>
            <% end %>
              <% if speech.comments.count.nonzero? %>
              <span>
                <% if user_signed_in? && current_user.comments.find_by(speech_id: speech.id) %>
                  <i class="fa fa-commenting-o speech-index-table__icon checked"></i>
                <% else %>
                  <i class="fa fa-commenting-o speech-index-table__icon"></i>
                <% end %>
                <%= speech.comments.count %>
              </span>
            <% end %>
          </span>
          </div>
          <div>
            <%= link_to user_speech_path(speech) do %>
              <button class="btn btn-info span12">スピーチを見る</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/help.html.erb
<% set_meta_tags home_help_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      Speech Linksの使い方
    </h1>
  </div>
  <div class="panel-body">
    <div class="home-contents">
      <section class="mbl">
        <h2>
          1.スピーチを登録しましょう！
        </h2>
        <p>
          <%= link_to new_user_speech_path do %>
            「<i class="fa fa-pencil-square-o"></i> スピーチ登録」
          <% end %>
          から自分のスピーチを登録できます。
        </p>
        <p>
          スピーチを登録すると、他のユーザーから「読んだ！」ボタンを押してもらえたり、コメントをもらえたりします。
        </p>
      </section>

      <section class="mbl">
        <h2>
          2.他の人のスピーチを読んでみましょう！
        </h2>
        <p>
          自分のスピーチを登録したら、他の人のスピーチを読んで見ましょう。
        </p>
        <p>
          メニューバー左側の「<i class="fa fa-book"></i> スピーチ一覧」や「<i class="fa fa-users"></i> Speaker一覧」から読みたいスピーチを探すことができます。
        </p>
        <p>
          <strong>他の人のスピーチを読んだら、「読んだ！」ボタン（<i class="fa fa-check-circle-o" style="color:red;"></i>）を押しましょう！</strong>
        </p>
        <p>
          また、スピーチの下のフォームから、そのスピーチにコメントを残すことができます。
        </p>
      </section>
    </div>
  </div>
</div>

app/views/home/privacy.html.erb
<% set_meta_tags home_privacy_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      プライバシーポリシー
    </h1>
  </div>
  <div class="panel-body">
    <div class="home-contents ptl pbl">
      SpeechLinks（以下,「本サービス」といいます。）におけるプライバシー情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。<br />
      <h2>
        第1条（プライバシー情報）
      </h2>
      * 		プライバシー情報のうち「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報を指します。<br />
      * 		プライバシー情報のうち「履歴情報および特性情報」とは，上記に定める「個人情報」以外のものをいい，ご利用いただいたサービスやご購入いただいた商品，ご覧になったページや広告の履歴，ユーザーが検索された検索キーワード，ご利用日時，ご利用の方法，ご利用環境，郵便番号や性別，職業，年齢，ユーザーのIPアドレス，クッキー情報，位置情報，端末の個体識別情報などを指します。<br />
      <h2>
        第２条（プライバシー情報の収集方法）
      </h2>
      * 		本サービスは，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や，決済に関する情報を本サービスの提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。<br />
      * 		本サービスは，ユーザーについて，利用したサービスやソフトウエア，購入した商品，閲覧したページや広告の履歴，検索した検索キーワード，利用日時，利用方法，利用環境（携帯端末を通じてご利用の場合の当該端末の通信状態，利用に際しての各種設定情報なども含みます），IPアドレス，クッキー情報，位置情報，端末の個体識別情報などの履歴情報および特性情報を，ユーザーが本サービスや提携先のサービスを利用しまたはページを閲覧する際に収集します。<br />
      <h2>
        第３条（個人情報を収集・利用する目的）
      </h2>
      本サービスが個人情報を収集・利用する目的は，以下のとおりです。<br />
      * 		（1）ユーザーに自分の登録情報の閲覧や修正，利用状況の閲覧を行っていただくために，氏名，住所，連絡先，支払方法などの登録情報，利用されたサービスや購入された商品，およびそれらの代金などに関する情報を表示する目的<br />
      * 		（2）ユーザーにお知らせや連絡をするためにメールアドレスを利用する場合やユーザーに商品を送付したり必要に応じて連絡したりするため，氏名や住所などの連絡先情報を利用する目的<br />
      * 		（3）ユーザーの本人確認を行うために，氏名，生年月日，住所，電話番号，銀行口座番号，クレジットカード番号，運転免許証番号，配達証明付き郵便の到達結果などの情報を利用する目的<br />
      * 		（4）ユーザーに代金を請求するために，購入された商品名や数量，利用されたサービスの種類や期間，回数，請求金額，氏名，住所，銀行口座番号やクレジットカード番号などの支払に関する情報などを利用する目的<br />
      * 		（5）ユーザーが簡便にデータを入力できるようにするために，本サービスに登録されている情報を入力画面に表示させたり，ユーザーのご指示に基づいて他のサービスなど（提携先が提供するものも含みます）に転送したりする目的<br />
      * 		（6）代金の支払を遅滞したり第三者に損害を発生させたりするなど，本サービスの利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの利用をお断りするために，利用態様，氏名や住所など個人を特定するための情報を利用する目的<br />
      * 		（7）ユーザーからのお問い合わせに対応するために，お問い合わせ内容や代金の請求に関する情報など本サービスがユーザーに対してサービスを提供するにあたって必要となる情報や，ユーザーのサービス利用状況，連絡先情報などを利用する目的<br />
      * 		（8）上記の利用目的に付随する目的<br />
      <h2>
        第４条（個人情報の第三者提供）
      </h2>
      * 		本サービスは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。<br />
      * 		（1）法令に基づく場合<br />
      * 		（2）人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br />
      * 		（3）公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br />
      * 		（4）国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br />
      * 		（5）予め次の事項を告知あるいは公表をしている場合<br />
      * 利用目的に第三者への提供を含むこと<br />
      * 第三者に提供されるデータの項目<br />
      * 第三者への提供の手段または方法<br />
      * 本人の求めに応じて個人情報の第三者への提供を停止すること<br />
      * 		前項の定めにかかわらず，次に掲げる場合は第三者には該当しないものとします。<br />
      * 		（1）本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合<br />
      * 		（2）合併その他の事由による事業の承継に伴って個人情報が提供される場合<br />
      * 		（3）個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いているとき<br />
      <h2>
        第５条（個人情報の開示）
      </h2>
      * 		本サービスは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。<br />なお，個人情報の開示に際しては，１件あたり１，０００円の手数料を申し受けます。<br />
      * 		（1）本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br />
      * 		（2）本サービスの業務の適正な実施に著しい支障を及ぼすおそれがある場合<br />
      * 		（3）その他法令に違反することとなる場合<br />
      * 		前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。<br />
      <h2>
        第６条（個人情報の訂正および削除）
      </h2>
      * 		ユーザーは，本サービスの保有する自己の個人情報が誤った情報である場合には，本サービスが定める手続きにより，本サービスに対して個人情報の訂正または削除を請求することができます。<br />
      * 		本サービスは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正または削除を行い，これをユーザーに通知します。<br />
      <h2>
        第７条（個人情報の利用停止等）
      </h2>
      本サービスは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行い，その結果に基づき，個人情報の利用停止等を行い，その旨本人に通知します。ただし，個人情報の利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，本人の権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じます。<br />
      <h2>
        第８条（プライバシーポリシーの変更）
      </h2>
      * 		本ポリシーの内容は，ユーザーに通知することなく，変更することができるものとします。<br />
      * 		本サービスが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。<br />
      <h2>
        第９条（お問い合わせ窓口）
      </h2>
      本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。<br />
       Eメールアドレス：official.speechlinks@gmail.com<br />
      以上<br />
    </div>
  </div>
</div>

app/views/home/terms.html.erb
<% set_meta_tags home_terms_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      利用規約
    </h1>
  </div>
  <div class="panel-body">
    <div class="home-contents ptl pbl">
      この利用規約（以下，「本規約」といいます。）は，SpeechLinks（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。<br />
      <h2>
        第1条（適用）
      </h2>
      本規約は，ユーザーと本サービスとの間の本サービスの利用に関わる一切の関係に適用されるものとします。<br />
      <h2>
        第2条（利用登録）
      </h2>
      登録希望者が本サービスの定める方法によって利用登録を申請し，本サービスがこれを承認することによって，利用登録が完了するものとします。<br />
      本サービスは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。<br />
      （1）利用登録の申請に際して虚偽の事項を届け出た場合<br />
      （2）本規約に違反したことがある者からの申請である場合<br />
      （3）未成年者，成年被後見人，被保佐人または被補助人のいずれかであり，法定代理人，後見人，保佐人または補助人の同意等を得ていなかった場合<br />
      （4）反社会的勢力等（暴力団，暴力団員，右翼団体，反社会的勢力，その他これに準ずる者を意味します。）である，または資金提供その他を通じて反社会的勢力等の維持，運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると本サービスが判断した場合<br />
      （5）その他，本サービスが利用登録を相当でないと判断した場合<br />
      <h2>
        第3条（ユーザーIDおよびパスワードの管理）
      </h2>
      ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。<br />
      ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。本サービスは，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。<br />
      <h2>
        第4条（利用料金および支払方法）
      </h2>
      ユーザーは，本サービス利用の対価として，本サービスが別途定め，本ウェブサイトに表示する利用料金を，本サービスが指定する方法により支払うものとします。<br />
      ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。<br />
      <h2>
        第5条（禁止事項）
      </h2>
      ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。<br />
      （1）法令または公序良俗に違反する行為<br />
      （2）犯罪行為に関連する行為<br />
      （3）本サービスのサーバーまたはネットワークの機能を破壊したり，妨害したりする行為<br />
      （4）本サービスのサービスの運営を妨害するおそれのある行為<br />
      （5）他のユーザーに関する個人情報等を収集または蓄積する行為<br />
      （6）他のユーザーに成りすます行為<br />
      （7）本サービスのサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為<br />
      （8）本サービス，本サービスの他の利用者または第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為<br />
      （9）過度に暴力的な表現，露骨な性的表現，人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現，自殺，自傷行為，薬物乱用を誘引または助長する表現，その他反社会的な内容を含み他人に不快感を与える表現を，投稿または送信する行為<br />
      （10）営業，宣伝，広告，勧誘，その他営利を目的とする行為（本サービスの認めたものを除きます。），性行為やわいせつな行為を目的とする行為，面識のない異性との出会いや交際を目的とする行為，他のお客様に対する嫌がらせや誹謗中傷を目的とする行為，その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為<br />
      （11）宗教活動または宗教団体への勧誘行為<br />
      （12）その他，本サービスが不適切と判断する行為<br />
      <h2>
        第6条（本サービスの提供の停止等）
      </h2>
      本サービスは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。<br />
      （1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br />
      （2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合<br />
      （3）コンピュータまたは通信回線等が事故により停止した場合<br />
      （4）その他，本サービスが本サービスの提供が困難と判断した場合<br />
      本サービスは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。<br />
      <h2>
        第7条（著作権）<br />
      </h2>
      ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報のみ，本サービスを利用し，投稿または編集することができるものとします。<br />
      ユーザーが本サービスを利用して投稿または編集した文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，本サービスは，本サービスを利用して投稿または編集された文章，画像，映像等を利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。<br />
      前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて本サービスまたは本サービスにその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。<br />
      <h2>
        第8条（利用制限および登録抹消）
      </h2>
      本サービスは，以下の場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。<br />
      （1）本規約のいずれかの条項に違反した場合<br />
      （2）登録事項に虚偽の事実があることが判明した場合<br />
      （3）破産，民事再生，会社更生または特別清算の手続開始決定等の申立がなされたとき<br />
      （4）1年間以上本サービスの利用がない場合<br />
      （5）本サービスからの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合<br />
      （6）第2条第2項各号に該当する場合<br />
      （7）その他，本サービスが本サービスの利用を適当でないと判断した場合<br />
      前項各号のいずれかに該当した場合，ユーザーは，当然に本サービスに対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。<br />
      本サービスは，本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。<br />
      <h2>
        第9条（保証の否認および免責事項）
      </h2>
      本サービスは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br />
      本サービスは，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する本サービスとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。<br />
      前項ただし書に定める場合であっても，本サービスは，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（本サービスまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。<br />
      本サービスは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。<br />
      <h2>
        第10条（サービス内容の変更等）
      </h2>
      本サービスは，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。<br />
      <h2>
        第11条（利用規約の変更）
      </h2>
      本サービスは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。<br />
      <h2>
        第12条（通知または連絡）
      </h2>
      ユーザーと本サービスとの間の通知または連絡は，本サービスの定める方法によって行うものとします。<br />
      <h2>
        第13条（権利義務の譲渡の禁止）
      </h2>
      ユーザーは，本サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。<br />
      <h2>
        第14条（準拠法・裁判管轄）
      </h2>
      本規約の解釈にあたっては，日本法を準拠法とします。<br />
      本サービスに関して紛争が生じた場合には，本サービスの本店所在地を管轄する裁判所を専属的合意管轄とします。<br />
      以上
    </div>
  </div>
</div>

app/views/home/top.html.erb
<% set_meta_tags home_top_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      ようこそ！SpeechLinksへ
    </h1>
  </div>
  <div class="panel-body">
    <section>
      <h2 class="top-speech-index__title">
        新着のスピーチ
      </h2>
      <%= render "speeches", speeches: @new_speeches %>
    </section>
    <section>
      <h2 class="top-speech-index__title">
        今のオススメスピーチ
      </h2>
      <%= render "speeches", speeches: @random_speeches %>
    </section>
    <section>
      <h2 class="top-speech-index__title">
        最近コメントされたスピーチ
      </h2>
      <%= render "speeches", speeches: @commented_speeches %>
    </section>
    <% if user_signed_in? %>
      <section>
        <h2 class="top-speech-index__title">
          自分のスピーチ
        </h2>
        <%= render "speeches", speeches: @my_speeches %>
      </section>
      <section>
        <h2 class="top-speech-index__title">
          最近読んだスピーチ
        </h2>
        <%= render "speeches", speeches: @my_liked_speeches %>
      </section>
    <% end %>
  </div>
</div>