config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#         new_user_session GET    /user/login(.:format)                            devise/sessions#new
#             user_session POST   /user/login(.:format)                            devise/sessions#create
#     destroy_user_session DELETE /user/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /user/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /user/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /user/password(.:format)                         devise/passwords#update
#                          PUT    /user/password(.:format)                         devise/passwords#update
#                          POST   /user/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /user/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /user/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /user(.:format)                                  devise/registrations#update
#                          PUT    /user(.:format)                                  devise/registrations#update
#                          DELETE /user(.:format)                                  devise/registrations#destroy
#                          POST   /user(.:format)                                  devise/registrations#create
#                     root GET    /                                                home#top
#                 home_top GET    /home/top(.:format)                              home#top
#                home_help GET    /home/help(.:format)                             home#help
#             home_privacy GET    /home/privacy(.:format)                          home#privacy
#               home_terms GET    /home/terms(.:format)                            home#terms
#                    users GET    /users(.:format)                                 users#index
#                          POST   /users(.:format)                                 users#create
#                 new_user GET    /users/new(.:format)                             users#new
#                edit_user GET    /users/:id/edit(.:format)                        users#edit
#                     user GET    /users/:id(.:format)                             users#show
#                          PATCH  /users/:id(.:format)                             users#update
#                          PUT    /users/:id(.:format)                             users#update
#                          DELETE /users/:id(.:format)                             users#destroy
#       user_notifications GET    /user/notifications(.:format)                    user/notifications#index
#        user_notification GET    /user/notifications/:id(.:format)                user/notifications#show
#        user_speech_likes GET    /user/speeches/:speech_id/likes(.:format)        user/likes#index
#                          POST   /user/speeches/:speech_id/likes(.:format)        user/likes#create
#         user_speech_like DELETE /user/speeches/:speech_id/likes/:id(.:format)    user/likes#destroy
#     user_speech_comments POST   /user/speeches/:speech_id/comments(.:format)     user/comments#create
#      user_speech_comment DELETE /user/speeches/:speech_id/comments/:id(.:format) user/comments#destroy
#            user_speeches GET    /user/speeches(.:format)                         user/speeches#index
#                          POST   /user/speeches(.:format)                         user/speeches#create
#          new_user_speech GET    /user/speeches/new(.:format)                     user/speeches#new
#         edit_user_speech GET    /user/speeches/:id/edit(.:format)                user/speeches#edit
#              user_speech GET    /user/speeches/:id(.:format)                     user/speeches#show
#                          PATCH  /user/speeches/:id(.:format)                     user/speeches#update
#                          PUT    /user/speeches/:id(.:format)                     user/speeches#update
#                          DELETE /user/speeches/:id(.:format)                     user/speeches#destroy
#              admin_likes GET    /admin/likes(.:format)                           admin/likes#index
#              admin_users GET    /admin/users(.:format)                           admin/users#index

Rails.application.routes.draw do

  devise_for :user, :path_names => {:sign_in => 'login'}
  root to: "home#top"
  get 'home/top'
  get 'home/help'
  get 'home/privacy'
  get 'home/terms'
  resources :users
  namespace :user do
    resources :notifications, only: [:index, :show]
    resources :speeches do
      resources :likes, only: [:create, :destroy, :index]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :likes, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/speech.rb
# == Schema Information
#
# Table name: speeches
#
#  id         :bigint(8)        not null, primary key
#  title      :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  overview   :text(65535)
#

class Speech < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  belongs_to :user
  has_many :liked_users, through: :likes, source: :user
  has_many :commented_users, through: :comments, source: :user
  has_many :notification, dependent: :delete_all

  validates :title, presence: true
  validates :content, presence: true
  validates :overview, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  bio                    :text(65535)
#  image                  :text(65535)
#  university             :integer
#  grade                  :integer
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :speeches, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  has_many :liked_speeches, through: :likes, source: :speech
  has_many :commented_speeches, through: :comments, source: :speech
  has_many :notification, dependent: :delete_all

  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :bio, presence: true
  validates :university, presence: true
  validates :grade, presence: true

  enum university: [
      :東京大学,
      :慶應義塾大学,
      :聖心女子大学,
      :津田塾大学,
      :筑波大学,
      :立教大学,
      :上智大学,
      :神奈川大学,
      :早稲田大学,
      :東京女子大学,
      :京都大学,
      :青山学院大学,
      :明治大学,
      :東京外国語大学,
      :同志社大学,
      :東北大学,
      :東京理科大学,
      :日本女子大学,
      :神戸市外語大学,
      :茨城大学,
      :獨協大学,
      :龍谷大学,
      :山口大学,
      :活水女子大学,
      :高崎経済大学,
      :ノートルダム清心女子大学,
      :昭和女子大学,
      :関西外語大学,
      :群馬県立女子大学,
      :岡山大学,
      :立命館大学,
      :法政大学,
      :北九州大学,
      :東京国際大学,
      :横浜市立大学,
      :そのほかの大学,
      :ESSのOBOG,
      :大学生以外
  ]

  def links_point
    links_point = 0
    self.speeches.each do |speech|
      links_point += 3
      links_point += speech.likes.count
      links_point += speech.comments.count
    end
    links_point += self.likes.count
    links_point += self.commented_speeches.count
    return links_point
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_comment_owner, only: [:destroy]
  after_action :create_notification, only: [:create]

  def create
    @speech = Speech.find(params[:speech_id])
    @comment = current_user.comments.new(comment_params)
    @comment.speech_id = params[:speech_id]
    if @comment.save
      redirect_to user_speech_path(@speech), notice: "コメントを投稿しました！"
    else
      redirect_to user_speech_path(@speech), alert: "コメント内容を入力してください"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to user_speech_path(params[:speech_id]), notice: "コメントを削除しました"
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def ensure_comment_owner
    @comment = Comment.find(params[:id])
    if current_user.id != @comment.user_id
      redirect_to user_speech_path(@comment.speech), alert: "他人のコメントは編集できません"
    end
  end

  def create_notification
    return if @speech.user_id == current_user.id
    Notification.create(
      user_id: @speech.user.id,
      notified_by_id: current_user.id,
      speech_id: @speech.id,
      notified_type: "コメント",
      read: false
    )
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  after_action :create_notification, only: [:create]

  def create
    @speech = Speech.find(params[:speech_id])
    @like = current_user.likes.new(speech_id: params[:speech_id])
    @like.save
    redirect_to user_speech_path(@speech.id)
  end

  def destroy
    @like = current_user.likes.find_by(speech_id: params[:speech_id])
    @like.delete
    redirect_to user_speech_path(params[:speech_id])
  end

  def index
    @speech = Speech.find(params[:speech_id])
    @users = @speech.liked_users
  end

  private
  def create_notification
    return if @speech.user_id == current_user.id
    Notification.create(
      user_id: @speech.user.id,
      notified_by_id: current_user.id,
      speech_id: @speech.id,
      notified_type: "読んだ！",
      read: false
    )
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notification = current_user.notification.order("created_at DESC")
  end

  def show
    @notification = Notification.find(params[:id])
    @notification.update(read: true)
    redirect_to user_speech_path(@notification.speech)
  end
end

app/controllers/user/speeches_controller.rb
class User::SpeechesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_speech_owner, only: [:edit, :update, :destroy]

  PER = 8

  def new
    @speech = Speech.new
  end

  def create
    @speech = current_user.speeches.new(speech_params)
    if @speech.save
      redirect_to user_speech_path(@speech), notice: "スピーチを登録しました"
    else
      render :new
    end
  end

  def show
    @speech = Speech.find(params[:id])
    @comments = @speech.comments
    @comment = Comment.new
  end

  def index
    @speeches = Speech.all.order("created_at DESC").page(params[:page]).per(PER)
  end

  def edit
    @speech = Speech.find(params[:id])
  end

  def update
    @speech = Speech.find(params[:id])
    if @speech.update(speech_params)
      @speech.save
      redirect_to user_speech_path(@speech), notice: "スピーチを更新しました"
    else
      render :edit
    end
  end

  def destroy
    @speech = Speech.find(params[:id])
    @speech.destroy
    redirect_to user_speeches_path, notice: "スピーチを削除しました。"
  end

  private
  def speech_params
    params.require(:speech).permit(:title, :content, :overview)
  end

  def ensure_speech_owner
    @speech = Speech.find(params[:id])
    if current_user.id != @speech.user_id
      redirect_to user_speech_path(@speech), alert: "他人のスピーチは編集できません"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :ensure_current_user, only: [:edit, :update]

  PER = 8

  def index
    @users = User.all.page(params[:page]).per(PER)
  end

  def show
    @user = User.find(params[:id])
    @speeches = @user.speeches.order("created_at DESC")
    @liked_speeches = @user.liked_speeches.order("created_at DESC")
    @commented_speeches = @user.commented_speeches.order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      @user.save
      redirect_to user_path(@user), notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :bio, :university, :grade, :image)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
      redirect_to user_speeches_path, alert: "他のユーザーの情報は編集できません"
    end
  end
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
  def user_likes_index_meta_tags
    {
      title: @speech.title,
      noindex: true
    }
  end
end

app/helpers/user/notifications_helper.rb
module User::NotificationsHelper
  def user_notifications_index_meta_tags
    {
      title: '通知一覧',
      noindex: true
    }
  end
end

app/helpers/user/speeches_helper.rb
module User::SpeechesHelper
  def user_speeches_edit_meta_tags
    {
      title: 'スピーチ編集',
      noidex: true
    }
  end

  def user_speeches_index_meta_tags
    {
      title: 'スピーチ一覧'
    }
  end

  def user_speeches_new_meta_tags
    {
      title: 'スピーチ新規作成',
      noidex: true
    }
  end

  def user_speeches_show_meta_tags
    {
      title: @speech.title,
      description: @speech.overview,
      og: {
        image: File.join(root_url, @speech.user.image.thumb.url)
      }
    }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def users_edit_meta_tags
    {
      title: 'プロフィール編集',
      noindex: true
    }
  end

  def users_index_meta_tags
    {
      title: 'スピーカー一覧'
    }
  end

  def users_show_meta_tags
    {
      title: @user.name,
      description: @user.bio,
      og: {
        image: File.join(root_url, @user.image.thumb.url)
      }
    }
  end
end

app/views/user/speeches/_like.html.erb
<div class="speech-like-pc pc-only">
  <div class="speech-like-pc__count">
    <%= link_to user_speech_likes_path(speech) do %>
      <%= speech.likes.count %>
    <% end %>
  </div>
  <div class="speech-like-pc__button">
    <% if user_signed_in? %>
      <% if speech.user_id == current_user.id %>
        <i class="fa fa-check-circle speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="自分のスピーチは読んだ！できません"></i>
      <% else %>
        <% if current_user.likes.find_by(speech_id: speech.id) %>
          <%= link_to user_speech_like_path(speech.id), method: :delete do %>
            <i class="fa fa-check-circle speech-like-pc__icon checked" data-toggle="tooltip" data-placement="bottom" data-original-title="読んだ！済み" aria-describedby="popover"></i>
          <% end %>
        <% else %>
          <%= link_to user_speech_likes_path(speech.id), method: :post do %>
            <i class="fa fa-check-circle-o speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="読んだ！を押す"></i>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fa fa-check-circle speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="ログインすると読んだ！を押すことができます"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user/speeches/_like_pc.html.erb
<div class="speech-like-pc pc-only">
  <div class="speech-like-pc__count">
    <%= link_to user_speech_likes_path(speech) do %>
      <%= speech.likes.count %>
    <% end %>
  </div>
  <div class="speech-like-pc__button">
    <% if user_signed_in? %>
      <% if speech.user_id == current_user.id %>
        <i class="fa fa-check-circle speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="自分のスピーチは読んだ！できません"></i>
      <% else %>
        <% if current_user.likes.find_by(speech_id: speech.id) %>
          <%= link_to user_speech_like_path(speech.id), method: :delete do %>
            <i class="fa fa-check-circle speech-like-pc__icon checked" data-toggle="tooltip" data-placement="bottom" data-original-title="読んだ！済み" aria-describedby="popover"></i>
          <% end %>
        <% else %>
          <%= link_to user_speech_likes_path(speech.id), method: :post do %>
            <i class="fa fa-check-circle-o speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="読んだ！を押す"></i>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fa fa-check-circle speech-like-pc__icon" data-toggle="tooltip" data-placement="bottom" data-original-title="ログインすると読んだ！を押すことができます"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user/speeches/_speeches.html.erb
<table class="table table-hover speech-index-table">
  <% speeches.each do |speech| %>
    <tr>
      <td>
        <div class="speech-index-table__title">
          <%= link_to(user_speech_path(speech)) do %>
            <span data-toggle="tooltip" data-placement="right" data-original-title="<%= speech.overview %>">
              <%= speech.title %>
            </span>
          <% end %>
        </div>
        <div class="pls">
          <span class="speech-index-table__user prs ">
            <%= link_to(user_path(speech.user)) do %>
              <%= image_tag speech.user.image.thumb.url, class: "speech-index-table__image user-image mrs" %>
              <%= speech.user.name %>
            <% end %>
          </span>
          <span class="speech-index-table__created">
            <%= speech.created_at %>
          </span>
        </div>
      </td>
      <td>
        <span class="speech-index-table__right">
          <% if speech.likes.count.nonzero? %>
            <p>
              <% if user_signed_in? && current_user.likes.find_by(speech_id: speech.id) %>
                <i class="fa fa-check-circle speech-index-table__icon checked"></i>
              <% else %>
                <i class="fa fa-check-circle speech-index-table__icon"></i>
              <% end %>
              <%= speech.likes.count %>
            </p>
          <% end %>
          <% if speech.comments.count.nonzero? %>
            <p>
              <% if user_signed_in? && current_user.comments.find_by(speech_id: speech.id) %>
                <i class="fa fa-commenting-o speech-index-table__icon checked"></i>
              <% else %>
                <i class="fa fa-commenting-o speech-index-table__icon"></i>
              <% end %>
              <%= speech.comments.count %>
            </p>
          <% end %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

app/views/user/speeches/edit.html.erb
<% set_meta_tags user_speeches_edit_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      スピーチを更新する
    </h1>
  </div>
  <div class="panel-body inner-m">
    <%= render "shared/error_message", model: @speech %>
    <%= form_for [:user, @speech] do |f| %>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "form-control speech-form__title mbm", placeholder: "タイトル" %>
      <%= f.label :overview, "紹介文" %>
      <%= f.text_area :overview, class: "form-control speech-form__overview mbm", rows: 3, placeholder: "例：皆さんは「みんなやっているから」という理由で決断をしてしまった経験はありませんか？このスピーチが「10年後の自分」を考えるきっかけになれば嬉しいです！添削としてではなく、皆さんの純粋な感想を聞かせてください！" %>
      <%= f.label :content, "本文（各段落の最初は全角スペース4つ分空けてください）" %>
      <%= f.text_area :content, class: "form-control speech-form__contents mbm", rows: 50, placeholder: "本文を書いてください（各段落の最初は全角スペース4つ分空けてください）" %>
      <%= f.submit "スピーチを更新する！", class: "btn btn-primary span12" %>
    <% end %>
  </div>
</div>

app/views/user/speeches/index.html.erb
<% set_meta_tags user_speeches_index_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      新着スピーチ一覧
    </h1>
  </div>
  <div class="panel-body">
    <%= render "speeches", speeches: @speeches %>
    <div class="text-center">
      <%= paginate @speeches %>
    </div>
  </div>
</div>

app/views/user/speeches/new.html.erb
<% set_meta_tags user_speeches_new_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      あなたのスピーチを登録しましょう！
    </h1>
  </div>
  <div class="panel-body inner-m">
    <%= render "shared/error_message", model: @speech %>
    <%= form_for [:user, @speech] do |f| %>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "form-control speech-form__title mbm", placeholder: "タイトル" %>
      <%= f.label :overview, "紹介文" %>
      <%= f.text_area :overview, class: "form-control speech-form__overview mbm", rows: 3, placeholder: "例：皆さんは「みんなやっているから」という理由で決断をしてしまった経験はありませんか？このスピーチが「10年後の自分」を考えるきっかけになれば嬉しいです！添削としてではなく、皆さんの純粋な感想を聞かせてください！" %>
      <%= f.label :content, "本文（各段落の最初は全角スペース4つ分空けてください）" %>
      <%= f.text_area :content, class: "form-control speech-form__contents mbm", rows: 50, placeholder: "本文を書いてください（各段落の最初は全角スペース4つ分空けてください）" %>
      <%= f.submit "スピーチを登録する！", class: "btn btn-primary span12" %>
    <% end %>
  </div>
</div>

app/views/user/speeches/show.html.erb
<% set_meta_tags user_speeches_show_meta_tags %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      <%= @speech.title %>
    </h1>
  </div>
  <div class="panel-body speech-container mbl">
    <div class="speech-overview mtm mbl">
      <blockquote class="span8">
        <p>
          <%= simple_format(@speech.overview) %>
        </p>
        <small>
          <%= link_to @speech.user.name, user_path(@speech.user) %>
        </small>
      </blockquote>
      <div class="speech-overview__right span4 mtm">
        <p>
          登録日時 : <%= @speech.created_at %>
        </p>
        <p>
          最終更新日時 : <%= @speech.updated_at %>
        </p>

        <% if user_signed_in? && @speech.user_id == current_user.id %>
          <%= link_to edit_user_speech_path(@speech), class: "btn btn-info" do %>
            <i class="fa fa-pencil-square-o"></i> 編集
          <% end %>
          <%= link_to user_speech_path(@speech), class: "btn btn-danger", method: :delete, data: {confirm: '本当にスピーチを削除しますか？'} do %>
            <i class="fa fa-trash-o"></i> 削除
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="speech-show mbl">
      <div class="speech-show__title">
        <%= @speech.title %>
      </div>
      <div class="speech-show__name mbm">
        <%= @speech.user.name %>
      </div>
      <div class="speech-show__content">
        <%= safe_join(@speech.content.split("\n"), tag(:br)) %>
      </div>
    </div>

    <div class="mbl">
      <p>
        現在<%= link_to @speech.likes.count, user_speech_likes_path(@speech) %>人がこのスピーチに「読んだ！」しています。
      </p>
      <% if user_signed_in? %>
        <% if @speech.user_id != current_user.id %>
          <% if current_user.likes.find_by(speech_id: @speech.id) %>
            <%= link_to user_speech_like_path(@speech.id), method: :delete, class: "btn btn-primary span12 mbm" do %>
              読んだ！済み
            <% end %>
          <% else %>
            <%= link_to user_speech_likes_path(@speech.id), method: :post, class: "btn btn-info span12 mbm" do %>
              読んだ！
            <% end %>
          <% end %>
        <% end %>
        <p>
          あなたは全部で<%= link_to current_user.likes.count, user_path(current_user) %>本のスピーチを読んでいます！
        </p>
      <% else %>
        <p>
          <%= link_to "ログイン", new_user_session_path %>すると読んだ記録を残すことができます
        </p>
      <% end %>
    </div>

    <%= render "like_pc", speech: @speech %>

    <div class="speech-comments">
      <table class="table speech-comments-table">
        <% @comments.each do |comment| %>
          <tr>
            <div class="panel panel-default">
              <div class="panel-heading">
                <span>
                  <%= link_to(user_path(comment.user)) do %>
                    <%= comment.user.name %>
                  <% end %>
                </span>
                <span class="speech-comments-table__right">
                  <% if user_signed_in? && current_user.id == comment.user_id %>
                    <%= link_to user_speech_comment_path(@speech.id, comment.id), method: :delete, data: {confirm: 'コメントを削除してよろしいですか？'} do %>
                      <i class="fa fa-trash-o"></i>
                    <% end %>
                  <% end %>
                  <%= comment.created_at %>
                </span>
              </div>
              <div class="panel-body speech-comments-table__text">
                <%= simple_format(comment.content) %>
              </div>
            </div>
          </tr>
        <% end %>
      </table>

      <% if user_signed_in? %>
        <div class="speech-comments-form">
          <%= render "shared/error_message", model: @comment %>
          <%= form_for (@comment), url: user_speech_comments_path(@speech) do |f| %>
            <%= f.label :content, "スピーチを読んだら感想を書いてあげましょう！" %>
            <%= f.text_area :content, class: "form-control speech-comments-form__text mbs", rows: 3, placeholder: "ご自身の体験がとても印象的で、心に残るスピーチでした！" %>
            <%= f.submit "コメントを投稿", class: "btn btn-primary span12" %>
          <% end %>
        </div>
      <% else %>
        <%= link_to "ログイン", new_user_session_path %>するとコメントを残すことができます
      <% end %>
    </div>
  </div>
</div>