config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#         new_user_session GET    /user/login(.:format)                            devise/sessions#new
#             user_session POST   /user/login(.:format)                            devise/sessions#create
#     destroy_user_session DELETE /user/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /user/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /user/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /user/password(.:format)                         devise/passwords#update
#                          PUT    /user/password(.:format)                         devise/passwords#update
#                          POST   /user/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /user/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /user/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /user(.:format)                                  devise/registrations#update
#                          PUT    /user(.:format)                                  devise/registrations#update
#                          DELETE /user(.:format)                                  devise/registrations#destroy
#                          POST   /user(.:format)                                  devise/registrations#create
#                     root GET    /                                                home#top
#                 home_top GET    /home/top(.:format)                              home#top
#                home_help GET    /home/help(.:format)                             home#help
#             home_privacy GET    /home/privacy(.:format)                          home#privacy
#               home_terms GET    /home/terms(.:format)                            home#terms
#                    users GET    /users(.:format)                                 users#index
#                          POST   /users(.:format)                                 users#create
#                 new_user GET    /users/new(.:format)                             users#new
#                edit_user GET    /users/:id/edit(.:format)                        users#edit
#                     user GET    /users/:id(.:format)                             users#show
#                          PATCH  /users/:id(.:format)                             users#update
#                          PUT    /users/:id(.:format)                             users#update
#                          DELETE /users/:id(.:format)                             users#destroy
#       user_notifications GET    /user/notifications(.:format)                    user/notifications#index
#        user_notification GET    /user/notifications/:id(.:format)                user/notifications#show
#        user_speech_likes GET    /user/speeches/:speech_id/likes(.:format)        user/likes#index
#                          POST   /user/speeches/:speech_id/likes(.:format)        user/likes#create
#         user_speech_like DELETE /user/speeches/:speech_id/likes/:id(.:format)    user/likes#destroy
#     user_speech_comments POST   /user/speeches/:speech_id/comments(.:format)     user/comments#create
#      user_speech_comment DELETE /user/speeches/:speech_id/comments/:id(.:format) user/comments#destroy
#            user_speeches GET    /user/speeches(.:format)                         user/speeches#index
#                          POST   /user/speeches(.:format)                         user/speeches#create
#          new_user_speech GET    /user/speeches/new(.:format)                     user/speeches#new
#         edit_user_speech GET    /user/speeches/:id/edit(.:format)                user/speeches#edit
#              user_speech GET    /user/speeches/:id(.:format)                     user/speeches#show
#                          PATCH  /user/speeches/:id(.:format)                     user/speeches#update
#                          PUT    /user/speeches/:id(.:format)                     user/speeches#update
#                          DELETE /user/speeches/:id(.:format)                     user/speeches#destroy
#              admin_likes GET    /admin/likes(.:format)                           admin/likes#index
#              admin_users GET    /admin/users(.:format)                           admin/users#index

Rails.application.routes.draw do

  devise_for :user, :path_names => {:sign_in => 'login'}
  root to: "home#top"
  get 'home/top'
  get 'home/help'
  get 'home/privacy'
  get 'home/terms'
  resources :users
  namespace :user do
    resources :notifications, only: [:index, :show]
    resources :speeches do
      resources :likes, only: [:create, :destroy, :index]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :likes, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--    meta-tagsの設定-->
    <%= display_meta_tags admin_meta_tags %>
    <!--    google analytics-->
    <%= analytics_init if Rails.env.production? %>
    <!--    CSRF対策-->
    <%= csrf_meta_tags %>
  </head>

  <body id="body">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
            <span class="sr-only">Speech Links</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand">Admin Mode</span>
        </div>
        <% if user_signed_in? %>
          <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-1" aria-expanded="true">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to admin_users_path do %>
                  <i class="fa fa-users"></i> ユーザー分析
                <% end %>
              </li>
              <li>
                <%= link_to admin_likes_path do %>
                  <i class="fa fa-check-circle"></i> 読んだ！一覧
                <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to user_speeches_path do %>
                  <i class="fa fa-sign-out"></i> ユーザーモードに戻る
                <% end %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>

    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible">
        <div class="container">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div class="alert alert-danger alert-dismissible">
        <div class="container">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
		</script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--    meta-tagsの設定-->
    <%= display_meta_tags default_meta_tags %>
    <!--    google analytics-->
    <%= analytics_init if Rails.env.production? %>
    <!--    CSRF対策-->
    <%= csrf_meta_tags %>
  </head>

  <body id="body">
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>

    <div class="container mbl">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>

    <script>
      // bootstrapのtooltip
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
		</script>
  </body>
</html>